version: "3.8"

services:

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_DATABASE: tododb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app

  frontend:
    build: ./frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app
    restart: unless-stopped

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-tododb}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-root}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - app

networks:
  app:
    driver: bridge
